### ISSUE TITLE
Occasional metric loss and hangs in DCGM Exporter

### ISSUE THREAD

**Issue by zlseu-edu** [NVIDIA/dcgm-exporter#164] opened 2023-06-01 13:13 UTC
I encountered a problem with DCGM Exporter where metrics occasionally go missing or hang. I have noticed that this issue does not occur consistently but happens intermittently, causing difficulties in monitoring and data analysis.

**Environment Information**

- DCGM Exporter version: 3.1.7-3.1.4
- Operating system: Ubuntu 20.04
- GPU model:  NVIDIA A100-PCIE-80GB
- Other relevant software and hardware environment information: run dcgm-exporter as daemonset in kubernetes.

**Expected Behavior**

I expected DCGM Exporter to consistently collect and export metric data according to the configuration, without experiencing occasional loss and hangs.

**Actual Behavior**

All GPU metrics suddenly hang.
![GPU Metrics hang](https://github.com/zlseu-edu/img/blob/master/GPU.PNG?raw=true)

dcgm-exporter metrics lost gpu2 util metric.
![DCGM metrics lost gpu2](https://github.com/zlseu-edu/img/blob/master/dcgm-exporter%20broken%20metrics.jpeg?raw=true)

no weired logs for dcgm-exporter and no kernel issues at that point. 
![dcgm-exporter pod log](https://github.com/zlseu-edu/img/blob/master/dcgm-pod-log.PNG?raw=true)

nvidia-smi can display real statistic. 
<img src="https://github.com/zlseu-edu/img/blob/master/nvidia-smi.PNG?raw=ture" width=350>

_After restart dcgm-exporter pod, everything works fine._

Please investigate this issue and provide support and guidance. Thank you!

**Comment by glowkey** [comment] 2023-06-02 17:18
Please re-test with 3.1.8-3.1.5. There was recently an issue fixed within DCGM itself that may have been the cause.

**Comment by zlseu-edu** [comment] 2023-06-03 03:43
> Please re-test with 3.1.8-3.1.5. There was recently an issue fixed within DCGM itself that may have been the cause.

Thanks! I will try next week.

**Comment by zlseu-edu** [comment] 2023-06-27 12:49
> Please re-test with 3.1.8-3.1.5. There was recently an issue fixed within DCGM itself that may have been the cause.

After upgrade to 3.1.8-3.1.5, issue still exists. :(

**Comment by henrixh** [comment] 2023-09-12 13:32
Currently on 'DCGM Exporter version 3.0.4-3.0.0', running on DGX A100. I can reproduce this (or a very similar issue) with a simple`systemctl restart nvidia-dcgm`. At that point, `dcgm-exporter` fails to connect and keeps sending out the last known values, until restarted. No attempt to reconnect with `nvidia-dcgm` seem to occur. 

Journal is spammed with the following message:

```
Xxx xx xx:xx:xx abcde123 dcgm-exporter[xxxxx]: time="202x-xx-xxTxx:xx:xx+xx:xx" level=error msg="Failed to collect metrics with error: Failed to collect metrics with error: Error getting the latest value for fields: Host engine connection invalid/disconnected"
```

The issue is resolved by restarting `dcgm-exporter`. One possible mitigation for us could be adding a `PartOf=nvidia-dcgm.service`, which we will probably add.

On a higher level, the exporter should not behave like this when loosing connection IMO. It should either fail hard or simply not yield any data so we get nulls in Prometheus, until it manages to reconnect. Serving stale data is the worst possible option.

**Comment by zlseu-edu** [comment] 2023-10-31 09:57
> Currently on 'DCGM Exporter version 3.0.4-3.0.0', running on DGX A100. I can reproduce this (or a very similar issue) with a simple`systemctl restart nvidia-dcgm`. At that point, `dcgm-exporter` fails to connect and keeps sending out the last known values, until restarted. No attempt to reconnect with `nvidia-dcgm` seem to occur.
> 
> Journal is spammed with the following message:
> 
> ```
> Xxx xx xx:xx:xx abcde123 dcgm-exporter[xxxxx]: time="202x-xx-xxTxx:xx:xx+xx:xx" level=error msg="Failed to collect metrics with error: Failed to collect metrics with error: Error getting the latest value for fields: Host engine connection invalid/disconnected"
> ```
> 
> The issue is resolved by restarting `dcgm-exporter`. One possible mitigation for us could be adding a `PartOf=nvidia-dcgm.service`, which we will probably add.
> 
> On a higher level, the exporter should not behave like this when loosing connection IMO. It should either fail hard or simply not yield any data so we get nulls in Prometheus, until it manages to reconnect. Serving stale data is the worst possible option.

as a workaround, I made a ops workflow to restart dcgm exporter pod after detect data was stale for 5min.

**Closed** 2024-03-15 17:04 UTC

**Comment by Rovanion** [comment] 2024-09-05 10:20
Hi,
Is this issue closed as in FIXED or WONTFIX? If it has been fixed, which release carries the fix?

**Comment by nvvfedorov** [comment] 2024-09-05 16:04
@Rovanion , Please test with the latest version of the dcgm-exporter. If the issue is still active, let's reopen.
